### ISSUE TITLE
New software

### ISSUE THREAD

**Issue by pklew** [Chauvetlighting/MavMK3Spot#5]
Install new software and chec
![copper tube changed](https://user-images.githubusercontent.com/96251510/146455853-74d20f99-0f2e-4a20-9dfa-efd63abc831e.jpg)
[Upload 03 Setup V1.0.zip](https://github.com/Chauvetlighting/MavMK3Spot/files/7730686/Upload.03.Setup.V1.0.zip)
k

**Comment by dgooch5200** [comment]
Testing done
